# SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-Forge-BuildScript-Exception
# build.conf plays a role similar to .env: machine/project-level
# configuration that the host forge injects into the build script's
# compilation via -DCONF_* macros. version is the single source of
# truth for the project version.
compiler=GCC
compiler_path=/usr/bin/gcc
version=v0.5
output_name=make # default value is "make"